---
- name: Fetch Jenkins Initial Admin Password
  hosts: jenkins
  gather_facts: false
  tasks:
    - name: Retrieve Jenkins Initial Admin Password
      command: sudo cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_initial_password
      become: true  # This will use sudo

    - name: Print Jenkins Initial Admin Password
      debug:
        msg: "Jenkins Initial Admin Password: {{ jenkins_initial_password.stdout }}"
